# Generated by Django 3.2.15 on 2022-10-04 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'verbose_name': 'Лист покупок', 'verbose_name_plural': 'Лист покупок'},
        ),
    ]
