name: Foodgram Test Workflow

on:

  push:
    branches: [ "tests" ]
    
jobs:

  deploy:
    name: run docker-compose
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: docker-compose up
        run: docker-compose --file ./infra/docker-compose.yml --env-file ./infra/.env up -d
      - name: foodgram up
        run: |
          docker-compose exec backend python manage.py migrate
          docker-compose exec backend python manage.py collectstatic --noinput
          docker-compose exec backend python manage.py load_ingredients